DIBZ/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DIBZ.Base;
using DIBZ.Logic;
using DIBZ.Logic.GameCatalog;
using DIBZ.Logic.Offer;
using DIBZ.Common.DTO;
using DIBZ.Logic.Auth;
using DIBZ.Common;
using DIBZ.Logic.Notification;
using DIBZ.Services;
using DIBZ.Filters;
using System.Configuration;
using DIBZ.Logic.NewsLetter;
using DIBZ.Logic.NewsFeed;
using DIBZ.Logic.SupportsQueries;
using DIBZ.Common.Model;

namespace DIBZ.Controllers
{
    public class DashboardController : BaseWebController
    {
        string hostName = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority);

        // GET: Dashboard

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public async Task<ActionResult> Index(int formatId = 0)
        {
            string userType = System.Web.Configuration.WebConfigurationManager.AppSettings["User"];
            if (userType == "Admin")
            {
                return this.Redirect("/Admin/Login");
            }
            ViewData["Error"] = TempData["Error"];
            LogHelper.LogInfo("Fetching dashboard data");

            var gameCatalogLogic = LogicContext.Create<GameCatalogLogic>();

            //get all GamesCatalog
            var gameCatalogs = await gameCatalogLogic.GetAllFeaturedGames();

            if (TempData["searchOfferData"] != null)
            {
                ViewBag.Offers = TempData["searchOfferData"];
                TempData["searchOfferData"] = null;
            }
            else
            {
                var offerLogic = LogicContext.Create<OfferLogic>();
                ViewBag.Offers = await offerLogic.GetAllOfferForDashboard(formatId);
            }
            return View(gameCatalogs);
        }
        public async Task<ActionResult> ViewAllOffers(int formatId)
        {
            if (TempData["Error"] != null)
                ViewData["Error"] = TempData["Error"];

            var offerLogic = LogicContext.Create<OfferLogic>();
            var allOffersData = await offerLogic.GetAllOffers(formatId);
            return View(allOffersData);
        }
        public async Task<ActionResult> Register(string id, string firstName, string surname, string nickName, string email, string password, string mobileNo, string birthYear, string postalCode, string address, bool? rememberMe = true)
        {
            var authLogic = LogicContext.Create<AuthLogic>();
            try
            {
                var User = authLogic.AddUpdateUser(Convert.ToInt32(id), firstName, surname, nickName, email, password, mobileNo, birthYear, postalCode, address);
                if (User != null)
                {
                    var loginSession = authLogic.CreateLoginSession(email, password, false);
                    Response.Cookies["AuthCookie"].Value = loginSession.Token;
                    if (rememberMe == true)
                    {
                        Response.Cookies["AuthCookie"].Expires = DateTime.Now.AddYears(1);
                    }

                    EmailTemplateHelper templates = new EmailTemplateHelper();
                    EmailTemplateResponse emailTemplateResponse = new EmailTemplateResponse();
                    DIBZ.Common.Model.EmailNotification Email = new DIBZ.Common.Model.EmailNotification();

                    var emailTemplateLogic = LogicContext.Create<EmailTemplateLogic>();
                    emailTemplateResponse = await emailTemplateLogic.GetEmailTemplate(EmailType.Email, EmailContentType.SignUp);

                    templates.AddParam(DIBZ.Common.Model.Contants.AppUserNickName, nickName);
                    templates.AddParam(DIBZ.Common.Model.Contants.UrlContactUs, string.Format("<a href='{0}'>here</a>", hostName + "/Dashboard/ContactUs"));
                    var emailBody = templates.FillTemplate(emailTemplateResponse.Body);

                    await emailTemplateLogic.SaveEmailNotification(email, emailTemplateResponse.Title, emailBody, EmailType.Email, Priority.Low);
                    EmailHelper.Email(email, emailTemplateResponse.Title, emailBody);

                    return Json(new { IsSuccess = true, AppUserName = loginSession.ApplicationUser.NickName, AppUserId = loginSession.ApplicationUserId }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { IsSuccess = false, fail = "Some Thing Wrong!" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { IsSuccess = false, fail = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }

        //public ActionResult Login(string email, string password, string rememberMe)
        public ActionResult Login(string email, string password, bool rememberMe)
        {
            try
            {
                var authLogic = LogicContext.Create<AuthLogic>();
                DIBZ.Common.Model.ApplicationUser ApplicationUser = new DIBZ.Common.Model.ApplicationUser();
                ApplicationUser.Email = email;
                ApplicationUser.Password = password;
                //AuthLogic.GetApplicationUserByEmail(email);

                var loginSession = authLogic.CreateLoginSession(email, password, false);
                Response.Cookies["AuthCookie"].Value = loginSession.Token;
                //if (rememberMe == "on")
                if (rememberMe)
                {
                    Response.Cookies["AuthCookie"].Expires = DateTime.Now.AddYears(1);
                }
                return Json(new { IsSuccess = true, AppUserName = loginSession.ApplicationUser.NickName, AppUserId = loginSession.ApplicationUserId }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.LogError("Login: ", ex);
                return Json(new { IsSuccess = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }


        }
        [AuthOp(LoggedInUserOnly = true)]
        public async Task<ActionResult> Logout()
        {
            if (Request.Cookies["AuthCookie"] != null)
            {
                var authLogic = LogicContext.Create<AuthLogic>();
                await authLogic.CloseLoginSession(Request.Cookies["AuthCookie"].Value);
                Response.Cookies["AuthCookie"].Expires = DateTime.Now.AddDays(-1);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Test()
        {

            new DIBZ.Services.ServerNotificationService().Send(CurrentLoginSession.ApplicationUserId.ToString(), "Here i am 1 !");
            return this.Json("you result", JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> CounterOffer()
        {
            var notificationLogic = LogicContext.Create<NotificationLogic>();
            DIBZ.Common.Model.Notification notification = new DIBZ.Common.Model.Notification();
            NotificationModel notificationModel = new NotificationModel();
            //if you want to store some addional data in notification info
            string Ingame = "Pock";
            var data = new { IntrestedUserName = "John! ", InGame = "Pock" };
            notificationModel.AdditionalData = Helpers.GetJson(data);
            notificationModel.AppUserId = Convert.ToInt32(CurrentLoginSession.ApplicationUserId);
            //Channel like Android,Ios,Web
            notificationModel.Channel = 0;
            notificationModel.Content = "is intrested in your " + Ingame + "";
            notificationModel.CreatedTime = DateTime.Now;
            notificationModel.LastError = "";
            notificationModel.OfferId = 4;
            notificationModel.Status = Convert.ToInt32(DIBZ.Common.Model.NotificationStatus.UnRead);
            notificationModel.Title = "Counter Intrest";
            notificationModel.NotificationType = Convert.ToInt32(DIBZ.Common.Model.NotificationType.Desktop);
            notificationModel.NotificationBusinessType = Convert.ToInt32(DIBZ.Common.Model.NotificationBusinessType.CounterOffer);
            //save notification in notification table
            notification = await notificationLogic.AddNotification(notificationModel);
            //sent notification to offer creater
            new DIBZ.Services.ServerNotificationService().CounterOffer(CurrentLoginSession.ApplicationUserId, notification.Id, notificationModel.Content, notificationModel.CreatedTime, notificationModel.AdditionalData);
            return this.Json("your counter offer notification has been sent to relevent person", JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> AcceptOffer()
        {
            //int countOfferAppUserId = 2;
            var notificationLogic = LogicContext.Create<NotificationLogic>();
            DIBZ.Common.Model.Notification notification = new DIBZ.Common.Model.Notification();
            NotificationModel notificationModel = new NotificationModel();
            //if you want to store some addional data in notification info
            List<int> appUsersbyGameID = new List<int>();
            appUsersbyGameID.Add(1);
            appUsersbyGameID.Add(2);
            foreach (var appUsersId in appUsersbyGameID)
            {
                string ForGame = "Pock";
                string By = "John";
                var data = new { By = "John! ", ForGame = "Pock" };
                notificationModel.AdditionalData = Helpers.GetJson(data);
                notificationModel.AppUserId = Convert.ToInt32(appUsersId);
                //Channel like Android,Ios,Web
                notificationModel.Channel = 0;
                notificationModel.Content = "You offer has been accepted for " + ForGame + " game by " + By + ".";
                notificationModel.CreatedTime = DateTime.Now;

DIBZ/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DIBZ.Base;
using DIBZ.Logic;

namespace DIBZ.Controllers
{
    public class FilesController : BaseController
    {
        // GET: Files
        public async Task<ActionResult> Index(int fileId)
        {
            var filesLogic = LogicContext.Create<FilesLogic>();
            var fileObj = await filesLogic.GetFileById(fileId);
            //if (fileObj == null)
                //throw new ApiException("File not found");
            return File(Server.MapPath("~/Uploads/" + fileObj.Id), "application/octet-stream", fileObj.Filename);
        }
    }
}

DIBZ/Views/Dashboard/ChangePassword.cshtml
@{
    ViewBag.Title = "Change password";
    Layout = null;
}

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8" />
    <title>DIBZ</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link href="@Url.Content("~/Content/assets/plugins/bootstrap/css/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/assets/plugins/font-awesome/css/font-awesome.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/assets/css/style.min.css")" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->

</head>
<body class="gray-bg">

    <!-- Banner Slider START HERE -->
    <div class="section-container">
        <!-- BEGIN container -->
        <div class="container">
            <!-- BEGIN row -->
            <div class="row row-space-30">
                <!-- BEGIN col-8 -->
                <div class="col-md-5 m-tp-20 bg-white p-35 col-md-offset-3">
                    <div class="content">
                        <!-- BEGIN LOGIN FORM -->
                        <form id="form" class="login-form" >
                            <h3 class="form-title text-center m-b-15"><b>New Password</b></h3>
                            <div class="alert alert-danger display-hide" style="display:none;">
                                <button class="close" data-close="alert"></button>
                                <span>
                                    Enter any username and password.
                                </span>
                            </div>

                            <div class="form-group">
                                @*<div class="alert p-10" id="divMessage" >
                                    @if (ViewData["Message"]!=null)
                                    {
                                        <p>@ViewData["Message"]&nbsp;<span>Please <a href="@Url.Action("Index", "Dashboard")">proceed here</a></span></p>
                                    }
                                    
                                </div>*@
                                <div id="lblMessage" class="alert p-10" style="display:none;">
                                    <p>Password has been changed successfully.<span>Please <a href="@Url.Action("Index", "Dashboard")">proceed here</a></span></p>
                                </div>
                                
                            </div>

                            <div class="form-group">
                                <input id="pwd" class="form-control" type="password" autocomplete="off" placeholder="New Password" name="password" required maxlength="60" />
                                <input id="appUserId"  type="hidden" value="@Request.QueryString["id"]" name="id" />
                                <input id="confirmPassword" type="password" class="form-control" name="cpass" placeholder="Confirm New Password" maxlength="40" required>
                            </div>
                            <div class="form-actions">
                                <button type="button" id="btnChangePwd" class="btn btn-danger btn-block uppercase" onclick="ChangePassword();" >Save</button>

                            </div>
                            <div id="lblErrorMessage" class="alert alert-danger" style="display:none;"></div>
                        </form>
                        <!-- END LOGIN FORM -->

                    </div>
                </div>
                <!-- END row -->
            </div>
            <!-- END container -->
        </div>

        <!-- Banner Slider END HERE -->

    </div>

    <!-- ================== BEGIN BASE JS ================== -->
    <script src="@Url.Content("~/Content/assets/plugins/jquery/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/plugins/bootstrap/js/bootstrap.min.js")"></script>

    <!-- ================== END BASE JS ================== -->

    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/Common.js")"></script>


    <script>
	$(document).ready(function() {

        $('#form').validate();

        $('#confirmPassword').rules('add', {
            equalTo: "#pwd",
            messages: {
                equalTo: 'Password and confirm password does not match.'
            }

        });
    });

        function ChangePassword()
        {
            debugger;
            $('#form').validate();
            if ($('#form').valid()) {

                //checking for strong password.
                var strongRegex = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,}$/;
                var pwd = $('#pwd').val().match(strongRegex);
                if (pwd == null) {
                    $('#lblErrorMessage').show();
                    $('#lblErrorMessage').text("Please enter password which should contain at least one digit, one lower case, one upper case and 8 from the mentioned characters. ");
                    return false;
                }
                var appUserId = $('#appUserId').val();

                @*$.ajax('@Url.Action("SetNewPassword", "Dashboard")', { id: appUserId, password: password })
                    .done(function (resp) {
                        if (resp.IsSuccess === true) {
                            //console.log("locations: " + resp.data[0].Address);

                            $('#lblMessage').show();
                           
                        }
                        else {
                            $('#lblErrorMessage').show();
                            $('#lblErrorMessage').text("Password doesn't change successfully please contact administrator.");
                        }
                    })
                    .fail(function () {
                        //alert("error");
                    })*@

                ajaxCall('@Url.Action("SetNewPassword", "Dashboard")', { id: appUserId, password: $('#pwd').val() }, function (resp) {

                    if (resp.IsSuccess === true) {
                        $('#lblMessage').show();
                        return true;

                        }
                    else {
                        $('#lblErrorMessage').show();
                        $('#lblErrorMessage').text("Password doesn't change successfully please contact administrator.");
                    }

                }, function (fail) {

                //alert(resp.fail);
                return false;
                }, function (err) {

                    //alert(err);
                    return false;
                });
            }
        }
    </script>

</body>

</html>

DIBZ/Views/Dashboard/ViewAllOffers.cshtml
@model List<DIBZ.Logic.Offer.OfferData>
@{
    ViewBag.Title = "View All Offers";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var AppUser = (DIBZ.Common.Model.ApplicationUser)ViewData["AppUser"];
}

@section CustomScripts{
<link rel="stylesheet" href="@Url.Content("~/Content/assets/plugins/datatables/dataTables.bootstrap.css")">
<link rel="stylesheet" href="@Url.Content("~/Content/assets/plugins/datatables/rowReorder.dataTables.min.css")">
<link rel="stylesheet" href="@Url.Content("~/Content/assets/plugins/datatables/responsive.dataTables.min.css")">

<script src="@Url.Content("~/Content/assets/plugins/datatables/jquery.dataTables.min.js")"></script>
<script src="@Url.Content("~/Content/assets/plugins/datatables/dataTables.rowReorder.min.js")"></script>
<script src="@Url.Content("~/Content/assets/plugins/datatables/dataTables.responsive.min.js")"></script>

<script>
    $(function () {
        $('.table').DataTable({
            "scrollX": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "lengthChange": true,
            "columnDefs": [{
                "targets": 'no-sort',
                "orderable": false,
                "order": []
            }],
            //rowReorder: {
            //    selector: 'td:nth-child(2)'
            //},
            responsive: true
        });
    });

    if ('@ViewData["Error"]' != '') {
            //$(".alert-danger").show();

            //setTimeout(function () {
            //    $(".alert-danger").fadeOut("slow")
            //}, 4000);
        $('#alert-modal').addClass("in");
        $('#alert-modal').show();
    }
    function hideAlertPopup() {
        $('#alert-modal').hide();
    }

    function ViewGamerDetail(id)
    {
        debugger;
        console.log("id: "+id);
            
        ajaxCall('@Url.Action("ViewGamerDetail", "Dashboard")', { id: id }, function (resp) {
                   if (resp.IsSuccess === true) {
                       console.log("gamer name: " + resp.GamerNickName);
                       //$(".modal-body #offeredGame").text(resp.OfferedGame);
                       $("#gamerNickName").text(resp.GamerNickName);
                       var imageId = resp.GamerImageId;
                       var source = "/Files/Index?fileId=" + imageId;    /*Url.Action("Index", "Files", new { fileId = @@imageId })*/
                       $("#gamerImageId").attr("src", source);
                       $("#gamer_detail_Proposal").text(resp.Proposal);
                       $("#gamer_detail_NoShows").text(resp.NoShows);
                       $("#gamer_detail_GamesSent").text(resp.GamesSent);

                       $("#gamer_detail_TestFails").text(resp.TestFail);
                       $("#gamer_detail_TestPass").text(resp.TestPass);
                       $("#gamer_detail_Dibz").text(resp.DIBz);

                        }
                }, function (fail) {

                }, function (err) {

                });
        }

    //hide DataTable info when no data in Table
    $(function () {
        if ($('.dataTables_empty').length > 0) {
            $('#DataTables_Table_0_info').css("display", "none");
            $('.dataTables_empty').css("display", "none");
        }
    })

</script>
}
<style>
    .current {
    color: black !important;
    }
    .paginate_button.current:hover {
    color: black !important;
    }
</style>
<div id="page-header" class="section-container page-header-container bg-black">
    <!-- BEGIN page-header-cover -->
    <div class="page-header-cover">
        <img src="@Url.Content("~/Content/assets/img/top-cover.jpg")" alt="">

    </div>
    <!-- END page-header-cover -->
    <!-- BEGIN container -->
    <div class="container">
        <h1 class="page-header"><b>VIEW ALL</b> OFFERS</h1>
    </div>
    <!-- END container -->
</div>

<div class="alert alert-danger" style="display:none;">
    @ViewData["Error"]
</div>

<!-- Banner Slider START HERE -->
<div class="section-container bg-white border-bottom-1">
    <!-- BEGIN container -->
    <div class="container">
        <!-- BEGIN row -->
        <div class="row row-space-10">
            <!-- BEGIN col-8 -->
            <div class="col-md-12">
                <div class="checkout-body">
                    <div class="table-responsive">
@if (AppUser == null)
{
    
        <table class="table">
            <thead>
                <tr>
                    <th width="15%" class="vtop text-center">GAME</th>
                    <th width="15%" class="vtop">GAME NAME</th>
                    <th width="15%" class="vtop">OFFERED BY</th>
                    <th width="12%" class="vtop">FORMAT</th>
                    <th width="12%" class="vtop">CATEGORY</th>
                    <th width="12%" class="vtop">CREATED ON</th>
                    <th class="vtop text-center">OFFER RESPONSE</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="@(item.Sequence%2==0 ?"alter-bg" : "alter-bg-odd")" data-dismiss="modal" data-toggle="modal" data-target=".login-modal" style="cursor:pointer">  
                        <td class="cart-product">

                            <img src="@Url.Action("Index","Files",new {fileId= item.GameImageId })" class="img-responsive rounded img-thumbnail img-scratch img-max-width" alt="">
                        </td>
                        <td>@item.GameName</td>
                        <td>@item.NickName</td>
                        <td>@item.GameFormat</td>
                        <td>@item.GameCategory</td>
                        <td>@item.OfferedTimeValue</td>
                        <td class="cart-total text-center">
                            

                        </td>
                    </tr>
                }
            </tbody>
        </table>

}
else
{
    <table class="table">
        <thead>
            <tr>
                <th width="15%" class="vtop text-center">GAME</th>
                <th width="15%" class="vtop">GAME NAME</th>
                <th width="15%" class="vtop">OFFERED BY</th>
                <th width="12%" class="vtop">FORMAT</th>
                <th width="12%" class="vtop">CATEGORY</th>
                <th width="12%" class="vtop">CREATED ON</th>
                <th class="vtop text-center">OFFER RESPONSE</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="@(item.Sequence%2==0 ?"alter-bg" : "alter-bg-odd")">
                    <td class="cart-product">

                        <img src="@Url.Action("Index","Files",new {fileId= item.GameImageId })" class="img-responsive rounded img-thumbnail img-scratch img-max-width" alt="">
                    </td>
                    <td>@item.GameName </td>
                    <td><a class="text-dec-none-hover" href="#" onclick="ViewGamerDetail(@item.AppUserId);" data-toggle="modal" data-target=".gamer-detail-modal">@item.NickName</a></td>
                    <td>@item.GameFormat</td>
                    <td>@item.GameCategory</td>
                    <td>@item.OfferedTimeValue</td>
                    <td class="cart-total text-center">
                        @*@if (AppUser != null)
                            {
                                if (AppUser.Id != item.AppUserId)
                                {
                                    <a href="@Url.Action("AddCounterOffer","CounterOffer",new { id = @item.OfferId})" cl class="btn btn-danger p-l-14 p-r-14 m-r-2 btn btn-danger p-t-2 p-b-2">REQUEST SWAP</a>
                                }
                                else
                                {
                                    <a href="#" cl class="btn btn-danger p-l-14 p-r-14 m-r-2 btn btn-danger p-t-2 p-b-2">REQUEST SWAP</a>
                                }


                            }
                            else
                            {
                                <button type="button"  id="btnSignin" data-toggle="modal" data-target=".login-modal" class="p-l-14 p-r-14 m-r-2 btn btn-default p-t-2 p-b-2">SIGN IN</button>
                            }*@

                        @if (AppUser != null)
                        {
                            if (AppUser.Id != item.AppUserId)
                            {
                                <a href="@Url.Action("AddCounterOffer","CounterOffer",new { id = @item.OfferId})" class="btn btn-danger m-p">Lets SWAP</a>
                            }
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
}
                            
                            
                            
</div>
                </div>
            </div>
            <!-- END col-8 -->
        </div>
        <!-- END row -->
    </div>
    <!-- END container -->
</div>
<!-- Banner Slider END HERE -->

<!-- Alert Modal dailouge START HERE -->
<div class="modal fade success-popup" id="alert-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display:none;">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog modal-sm vertical-align-center">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title" id="myModalLabel">Alert !</h4>
                </div>
                <div class="modal-body text-center p-20">
                    <p>@ViewData["Error"]</p>

                </div>
                <div class="modal-footer text-center">
                    <a onclick="hideAlertPopup();" class="btn btn-danger btn-md" data-dismiss="modal">OK</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Alert Modal dailouge END HERE -->

<!-- User detai dailouge START HERE -->
<div class="modal fade gamer-detail-modal" tabindex='-1'>
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">GAME OFFERER DETAILS</h4>
                </div>
                <form id="frmCreateOffer">
                    <div class="modal-body">
                        
                    </div>
                    <div class="row row-space-10">
                        <!-- BEGIN col-8 -->
                        <div class="col-md-12">
                            <!-- Left Main Game START here -->
                            <div class="col-md-5">
                                <div class="product-img p-t-30">

                                    <img id="gamerImageId" alt="" class="img-responsive img-res" />
                                </div>
                                <div class="profile-usertitle">
                                    <h4 id="gamerNickName" class="profile-game-title m-t-0"></h4>
                                </div>
                            </div>
                            <!-- Left Main Game END here -->
                            <!-- Mid Description START here -->
                            <div class="col-md-7">
                                <div>
                                    <h3 class="counter-desc-title m-t-0">Scorecard</h3>
                                    <div class="form-group p-t-10 p-b-5 m-b-0 p-l-0 p-r-0 border-bottom-1">
                                        
                                        
                                        <div class="border-bottom-1 p-5"><b>Proposals:</b> <span class="pull-right" id="gamer_detail_Proposal"></span></div>
                                        <div class="border-bottom-1 p-5"><b>No shows:</b> <span class="pull-right" id="gamer_detail_NoShows"></span></div>
                                        <div class="border-bottom-1 p-5"><b>Games sent:</b> <span class="pull-right" id="gamer_detail_GamesSent"></span></div>
                                        <div class="border-bottom-1 p-5"><b>Test Fails:</b> <span class="pull-right" id="gamer_detail_TestFails"></span></div>
                                        <div class="border-bottom-1 p-5"><b>Test Pass:</b> <span class="pull-right" id="gamer_detail_TestPass"></span></div>
                                        <div class="border-bottom-1 p-5"><b>DIBz:</b> <span class="pull-right" id="gamer_detail_Dibz"></span></div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                            <!-- Mid Description END here -->
                        </div>
                        <!-- END col-8 -->
                    </div>
                </form>
                <div class="modal-footer">
                    <input type="button" name="cancel" data-dismiss="modal" class="btn btn-default btn-md" value="Close">
                </div>
            </div>


        </div>
    </div>
</div>
<!-- User details dailouge END HERE -->